name: Eastern District Conference
favicon: null
layout_spectrum: 0.253
typography_spectrum: 0.50812
title: Eastern District Conference
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17335a'
    - '#ff520b'
    - '#7b3929'
    - '#fefada'
    - '#f8ff01'
  brandStrength: 0.06376547925174236
  lightness: 0.4678673204034567
  saturation: 0.6233072155155241
  rhythmicContrast: 0.34083842672407627
purpose: []
