name: Eastern District Conference
favicon: null
layout_spectrum: 0.76249
typography_spectrum: 0.50812
title: Eastern District Conference
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17335a'
    - '#ff520b'
    - '#7b3929'
    - '#fefada'
    - '#f8ff01'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
